
DEBUG_LOG=1


LEVEL_BASE=0
LEVEL_DBG=LEVEL_BASE+1
LEVEL_HINT=LEVEL_BASE+5
LEVEL_IMPORTANT=LEVEL_BASE+8
LEVEL_WARNING=LEVEL_BASE+10
LEVEL_ERROR=LEVEL_BASE+100
KIND_PARENT="parent"
KIND_CHILD="child"
KIND_ALL="all"
