#!/usr/bin/env python
#encoding=utf-8
#first author:wangfei
import os
import glob
import sys
import shutil




if __name__ == '__main__':
    if os.path.exists("zprojects/scripts"):
        sys.path.append(os.path.abspath('zprojects/scripts'))
        sys.path.append(os.path.abspath("zprojects/scripts/plugins"))
        from vanzo_worker import VanzoWorker
        from bridge import *
        from project import Project
        from project_manager import ProjectManager
    manager=ProjectManager()
    manager.dispatch(sys.argv[1],sys.argv[2:])
    #manager.new_project_from(sys.argv[1:])
    #manager.compile_project(sys.argv[1:])
    #sys.exit()
